#!/bin/bash
set -euo pipefail

# ─── Canon Camera Sync — Installer ─────────────────────────────────────────────
# Reads config.yml and installs the udev rule, systemd service, and sync script.
# Must be run as root (sudo ./install.sh).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.yml"

# ─── Preflight checks ──────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root. Use: sudo ./install.sh"
    exit 1
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: config.yml not found."
    echo "Copy config.example.yml to config.yml and edit it first:"
    echo "  cp config.example.yml config.yml"
    exit 1
fi

if ! command -v gphoto2 &>/dev/null; then
    echo "WARNING: 'gphoto2' is not installed. The sync script will not work without it."
    echo "  Debian/Ubuntu: sudo apt install gphoto2"
    echo "  Fedora:        sudo dnf install gphoto2"
    echo "  Arch:          sudo pacman -S gphoto2"
fi

# Parse a value from flat YAML (key: value). Strips comments and quotes.
yml_get() {
    local val
    val=$(grep -E "^${1}:" "$CONFIG_FILE" | head -1 | sed "s/^${1}:[[:space:]]*//" | sed 's/[[:space:]]*#.*//' | sed 's/^["'\'']\(.*\)["'\'']$/\1/')
    echo "$val"
}

# ─── Read configuration ────────────────────────────────────────────────────────

VENDOR_ID="$(yml_get camera_vendor_id)"
PRODUCT_ID="$(yml_get camera_product_id)"
SCRIPT_INSTALL_DIR="$(yml_get script_dir)"
PRE_DELAY="$(yml_get pre_delay_seconds)"
DEST_BASE="$(yml_get dest_base)"

if [[ "$DEST_BASE" == "/path/to/your/photo/destination" ]]; then
    echo "ERROR: config.yml still has placeholder values. Edit it before installing."
    exit 1
fi

# ─── Validate configuration values ───────────────────────────────────────────
# Prevent injection via crafted config.yml values used in generated files.

if ! [[ "$VENDOR_ID" =~ ^[0-9a-fA-F]{4}$ ]]; then
    echo "ERROR: camera_vendor_id must be a 4-character hex string (e.g. 04a9)."
    exit 1
fi
if ! [[ "$PRODUCT_ID" =~ ^[0-9a-fA-F]{4}$ ]]; then
    echo "ERROR: camera_product_id must be a 4-character hex string (e.g. 32f9)."
    exit 1
fi
if ! [[ "$PRE_DELAY" =~ ^[0-9]+$ ]]; then
    echo "ERROR: pre_delay_seconds must be a positive integer."
    exit 1
fi
if [[ "$SCRIPT_INSTALL_DIR" != /* ]]; then
    echo "ERROR: script_dir must be an absolute path."
    exit 1
fi
if [[ "$SCRIPT_INSTALL_DIR" == *".."* || "$SCRIPT_INSTALL_DIR" == *";"* || "$SCRIPT_INSTALL_DIR" == *"&"* ]]; then
    echo "ERROR: script_dir contains invalid characters."
    exit 1
fi
if [[ "$DEST_BASE" != /* ]]; then
    echo "ERROR: dest_base must be an absolute path."
    exit 1
fi

echo "Installing canon-camera-sync..."
echo "  Vendor ID:    $VENDOR_ID"
echo "  Product ID:   $PRODUCT_ID"
echo "  Script dir:   $SCRIPT_INSTALL_DIR"
echo "  Destination:  $DEST_BASE"
echo ""

# ─── Install script files ──────────────────────────────────────────────────────

mkdir -p "$SCRIPT_INSTALL_DIR"
cp "$SCRIPT_DIR/camera-sync.sh" "$SCRIPT_INSTALL_DIR/camera-sync.sh"
cp "$SCRIPT_DIR/config.yml" "$SCRIPT_INSTALL_DIR/config.yml"
chmod +x "$SCRIPT_INSTALL_DIR/camera-sync.sh"
echo "  [OK] Script installed to $SCRIPT_INSTALL_DIR/"

# ─── Generate and install udev rule ────────────────────────────────────────────

UDEV_RULE="/etc/udev/rules.d/99-canon-camera-sync.rules"
cat > "$UDEV_RULE" <<EOF
# Auto-generated by install.sh — do not edit manually.
# To change, edit config.yml and re-run: sudo ./install.sh
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="$VENDOR_ID", ATTR{idProduct}=="$PRODUCT_ID", MODE="0660", GROUP="plugdev", TAG+="systemd", ENV{SYSTEMD_WANTS}="canon-camera-sync.service"
EOF
echo "  [OK] udev rule installed to $UDEV_RULE"

# ─── Generate and install systemd service ──────────────────────────────────────

# Where camera-sync.sh writes its Prometheus metrics. Kept in step with the
# default inside camera-sync.sh (CANON_SYNC_METRICS_DIR overrides both).
METRICS_DIR="/var/lib/node_exporter/textfile_collector"
SERVICE_FILE="/etc/systemd/system/canon-camera-sync.service"
# Generated from the checked-in template so the hardening set exists in exactly
# one place. Only the four @MARKER@ values are substituted, and each has already
# been validated above — nothing unvalidated reaches the unit file.
TEMPLATE="$SCRIPT_DIR/camera-sync.service"
if [[ ! -f "$TEMPLATE" ]]; then
    echo "ERROR: unit template not found at $TEMPLATE"
    exit 1
fi
sed -e "s|@PRE_DELAY@|$PRE_DELAY|g" \
    -e "s|@SCRIPT_DIR@|$SCRIPT_INSTALL_DIR|g" \
    -e "s|@DEST_BASE@|$DEST_BASE|g" \
    -e "s|@METRICS_DIR@|$METRICS_DIR|g" \
    "$TEMPLATE" > "$SERVICE_FILE"
if grep -q '@[A-Z_]*@' "$SERVICE_FILE"; then
    echo "ERROR: unsubstituted markers left in $SERVICE_FILE:"
    grep -o '@[A-Z_]*@' "$SERVICE_FILE" | sort -u
    exit 1
fi
echo "  [OK] systemd service installed to $SERVICE_FILE"

# ─── Generate and install the Wi-Fi event path ─────────────────────────────────
# Three more units, all optional in the sense that the USB path works without
# them — but without them there IS no Wi-Fi path, and "the sync runs when the
# camera comes online" is only half true. They were previously left to a set of
# install commands in the README, which meant a fresh install silently had no
# wireless trigger at all.
#
# canon-camera-watch.service is the event source: it listens for the camera's
# SSDP announcement and starts the sync the moment the camera joins the network.
# The timer is the backstop for an announcement lost to multicast.
#
# RequiresMountsFor needs the mount point holding dest_base, not dest_base
# itself, so systemd waits for the photo drive rather than a directory on it.
#
# dest_base is not created until further down, and on a fresh install it does
# not exist yet — findmnt cannot resolve a path that is not there. Walk up to
# the deepest ancestor that does exist and ask about that instead; on an
# already-mounted drive that is the drive, and before the first install it
# degrades to / rather than failing.
MOUNT_PROBE="$DEST_BASE"
while [[ -n "$MOUNT_PROBE" && ! -d "$MOUNT_PROBE" ]]; do
    MOUNT_PROBE="${MOUNT_PROBE%/*}"
done
[[ -n "$MOUNT_PROBE" ]] || MOUNT_PROBE=/
DEST_MOUNT="$(findmnt -no TARGET --target "$MOUNT_PROBE" 2>/dev/null || echo /)"
if [[ "$DEST_MOUNT" == "/" ]]; then
    echo "  [!!] dest_base is not on a separate mount; the Wi-Fi unit will not"
    echo "       wait for a drive before running. Re-run install.sh once the"
    echo "       photo drive is mounted if that is not what you want."
fi

install_unit() {
    local template="$SCRIPT_DIR/$1" target="/etc/systemd/system/$2"
    if [[ ! -f "$template" ]]; then
        echo "ERROR: unit template not found at $template"
        exit 1
    fi
    sed -e "s|@SCRIPT_DIR@|$SCRIPT_INSTALL_DIR|g" \
        -e "s|@DEST_BASE@|$DEST_BASE|g" \
        -e "s|@DEST_MOUNT@|$DEST_MOUNT|g" \
        -e "s|@METRICS_DIR@|$METRICS_DIR|g" \
        -e "s|@PRE_DELAY@|$PRE_DELAY|g" \
        "$template" > "$target"
    if grep -q '@[A-Z_]*@' "$target"; then
        echo "ERROR: unsubstituted markers left in $target:"
        grep -o '@[A-Z_]*@' "$target" | sort -u
        exit 1
    fi
    echo "  [OK] $2 installed"
}

CAMERA_MAC="$(yml_get camera_mac)"
if [[ -n "$CAMERA_MAC" ]]; then
    install -m755 "$SCRIPT_DIR/canon-camera-watch.py" "$SCRIPT_INSTALL_DIR/"
    install_unit camera-sync-wifi.service   canon-camera-sync-wifi.service
    install_unit camera-sync-wifi.timer     canon-camera-sync-wifi.timer
    install_unit canon-camera-watch.service canon-camera-watch.service
    WIFI_UNITS=1
else
    # No MAC means the Wi-Fi transport is disabled in camera-sync.sh anyway, so
    # installing units that can only ever report "no camera_mac set" would be
    # noise. Set camera_mac and re-run this script to turn the path on.
    echo "  [--] Wi-Fi units skipped: camera_mac is not set in config.yml"
    WIFI_UNITS=0
fi

# ─── Create the metrics directory ──────────────────────────────────────────────
# node_exporter's textfile collector reads *.prom from here and Prometheus
# scrapes them, which is what feeds the Grafana dashboard. 0755 is required:
# node_exporter runs as uid 65534 with cap_drop=ALL, so it can only traverse and
# read world-readable paths. Harmless to create even if no monitoring stack is
# installed — the script just writes a file nothing reads.
mkdir -p "$METRICS_DIR"
chmod 0755 /var/lib/node_exporter "$METRICS_DIR"
echo "  [OK] metrics directory ready at $METRICS_DIR"

# ─── Create destination directory ──────────────────────────────────────────────

OWNER_USER="$(yml_get owner_user)"
OWNER_GROUP="$(yml_get owner_group)"

if ! id -u "$OWNER_USER" &>/dev/null; then
    echo "ERROR: owner_user '$OWNER_USER' does not exist on this system."
    exit 1
fi
if ! getent group "$OWNER_GROUP" &>/dev/null; then
    echo "ERROR: owner_group '$OWNER_GROUP' does not exist on this system."
    exit 1
fi

mkdir -p "$DEST_BASE"
chown "$OWNER_USER:$OWNER_GROUP" "$DEST_BASE"
echo "  [OK] Destination directory created: $DEST_BASE"

# Bookkeeping for the geotag review: what the card looked like the last time
# each file was examined, plus the list of files the camera can no longer help
# with. Dot-prefixed so Immich's external-library crawler ignores it, and inside
# dest_base because the unit's ReadWritePaths= grants write access to nothing
# else. Created here so a first run does not have to.
mkdir -p "$DEST_BASE/.geo"
chown -R "$OWNER_USER:$OWNER_GROUP" "$DEST_BASE/.geo"
echo "  [OK] Geotag review state directory ready at $DEST_BASE/.geo"

# ─── Reload system daemons ─────────────────────────────────────────────────────

udevadm control --reload-rules
systemctl daemon-reload
echo "  [OK] udev rules and systemd reloaded"

if (( WIFI_UNITS )); then
    # enable --now on both: the watcher must be listening before the camera is
    # next switched on, and the timer's OnBootSec only fires at boot.
    systemctl enable --now canon-camera-watch.service >/dev/null 2>&1 \
        && echo "  [OK] canon-camera-watch.service enabled (SSDP trigger)" \
        || echo "  [!!] could not enable canon-camera-watch.service"
    systemctl enable --now canon-camera-sync-wifi.timer >/dev/null 2>&1 \
        && echo "  [OK] canon-camera-sync-wifi.timer enabled (30-minute backstop)" \
        || echo "  [!!] could not enable canon-camera-sync-wifi.timer"
fi

echo ""
echo "Installation complete!"
echo ""
echo "Test by connecting your camera, then check logs with:"
echo "  journalctl -u canon-camera-sync.service -f"
echo ""
echo "Or run the sync manually:"
echo "  sudo $SCRIPT_INSTALL_DIR/camera-sync.sh"
