#!/bin/bash
set -euo pipefail

# ─── Canon Camera Sync — Installer ─────────────────────────────────────────────
# Reads config.yml and installs the udev rule, systemd service, and sync script.
# Must be run as root (sudo ./install.sh).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.yml"

# ─── Preflight checks ──────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root. Use: sudo ./install.sh"
    exit 1
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: config.yml not found."
    echo "Copy config.example.yml to config.yml and edit it first:"
    echo "  cp config.example.yml config.yml"
    exit 1
fi

if ! command -v gphoto2 &>/dev/null; then
    echo "WARNING: 'gphoto2' is not installed. The sync script will not work without it."
    echo "  Debian/Ubuntu: sudo apt install gphoto2"
    echo "  Fedora:        sudo dnf install gphoto2"
    echo "  Arch:          sudo pacman -S gphoto2"
fi

# Parse a value from flat YAML (key: value). Strips comments and quotes.
yml_get() {
    local val
    val=$(grep -E "^${1}:" "$CONFIG_FILE" | head -1 | sed "s/^${1}:[[:space:]]*//" | sed 's/[[:space:]]*#.*//' | sed 's/^["'\'']\(.*\)["'\'']$/\1/')
    echo "$val"
}

# ─── Read configuration ────────────────────────────────────────────────────────

VENDOR_ID="$(yml_get camera_vendor_id)"
PRODUCT_ID="$(yml_get camera_product_id)"
SCRIPT_INSTALL_DIR="$(yml_get script_dir)"
PRE_DELAY="$(yml_get pre_delay_seconds)"
DEST_BASE="$(yml_get dest_base)"

if [[ "$DEST_BASE" == "/path/to/your/photo/destination" ]]; then
    echo "ERROR: config.yml still has placeholder values. Edit it before installing."
    exit 1
fi

# ─── Validate configuration values ───────────────────────────────────────────
# Prevent injection via crafted config.yml values used in generated files.

if ! [[ "$VENDOR_ID" =~ ^[0-9a-fA-F]{4}$ ]]; then
    echo "ERROR: camera_vendor_id must be a 4-character hex string (e.g. 04a9)."
    exit 1
fi
if ! [[ "$PRODUCT_ID" =~ ^[0-9a-fA-F]{4}$ ]]; then
    echo "ERROR: camera_product_id must be a 4-character hex string (e.g. 32f9)."
    exit 1
fi
if ! [[ "$PRE_DELAY" =~ ^[0-9]+$ ]]; then
    echo "ERROR: pre_delay_seconds must be a positive integer."
    exit 1
fi
if [[ "$SCRIPT_INSTALL_DIR" != /* ]]; then
    echo "ERROR: script_dir must be an absolute path."
    exit 1
fi
if [[ "$SCRIPT_INSTALL_DIR" == *".."* || "$SCRIPT_INSTALL_DIR" == *";"* || "$SCRIPT_INSTALL_DIR" == *"&"* ]]; then
    echo "ERROR: script_dir contains invalid characters."
    exit 1
fi
if [[ "$DEST_BASE" != /* ]]; then
    echo "ERROR: dest_base must be an absolute path."
    exit 1
fi

echo "Installing canon-camera-sync..."
echo "  Vendor ID:    $VENDOR_ID"
echo "  Product ID:   $PRODUCT_ID"
echo "  Script dir:   $SCRIPT_INSTALL_DIR"
echo "  Destination:  $DEST_BASE"
echo ""

# ─── Install script files ──────────────────────────────────────────────────────

mkdir -p "$SCRIPT_INSTALL_DIR"
cp "$SCRIPT_DIR/camera-sync.sh" "$SCRIPT_INSTALL_DIR/camera-sync.sh"
cp "$SCRIPT_DIR/config.yml" "$SCRIPT_INSTALL_DIR/config.yml"
chmod +x "$SCRIPT_INSTALL_DIR/camera-sync.sh"
echo "  [OK] Script installed to $SCRIPT_INSTALL_DIR/"

# ─── Generate and install udev rule ────────────────────────────────────────────

UDEV_RULE="/etc/udev/rules.d/99-canon-camera-sync.rules"
cat > "$UDEV_RULE" <<EOF
# Auto-generated by install.sh — do not edit manually.
# To change, edit config.yml and re-run: sudo ./install.sh
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="$VENDOR_ID", ATTR{idProduct}=="$PRODUCT_ID", MODE="0660", GROUP="plugdev", TAG+="systemd", ENV{SYSTEMD_WANTS}="canon-camera-sync.service"
EOF
echo "  [OK] udev rule installed to $UDEV_RULE"

# ─── Generate and install systemd service ──────────────────────────────────────

SERVICE_FILE="/etc/systemd/system/canon-camera-sync.service"
cat > "$SERVICE_FILE" <<'SERVICEEOF'
# Auto-generated by install.sh — do not edit manually.
# To change, edit config.yml and re-run: sudo ./install.sh

[Unit]
Description=Canon Camera Photo Sync
After=local-fs.target

[Service]
Type=oneshot
SERVICEEOF
# Write config-dependent lines separately with validated values
{
    echo "ExecStartPre=/bin/sleep $PRE_DELAY"
    echo "ExecStart=$SCRIPT_INSTALL_DIR/camera-sync.sh"
    echo "StandardOutput=journal"
    echo "StandardError=journal"
    echo ""
    echo "# Hardening"
    echo "NoNewPrivileges=yes"
    echo "ProtectSystem=strict"
    echo "ProtectHome=read-only"
    echo "PrivateTmp=yes"
    echo "ProtectKernelTunables=yes"
    echo "ProtectKernelModules=yes"
    echo "ProtectControlGroups=yes"
    echo "RestrictRealtime=yes"
    echo "MemoryDenyWriteExecute=yes"
    echo "ReadWritePaths=$DEST_BASE"
} >> "$SERVICE_FILE"
echo "  [OK] systemd service installed to $SERVICE_FILE"

# ─── Create destination directory ──────────────────────────────────────────────

OWNER_USER="$(yml_get owner_user)"
OWNER_GROUP="$(yml_get owner_group)"

if ! id -u "$OWNER_USER" &>/dev/null; then
    echo "ERROR: owner_user '$OWNER_USER' does not exist on this system."
    exit 1
fi
if ! getent group "$OWNER_GROUP" &>/dev/null; then
    echo "ERROR: owner_group '$OWNER_GROUP' does not exist on this system."
    exit 1
fi

mkdir -p "$DEST_BASE"
chown "$OWNER_USER:$OWNER_GROUP" "$DEST_BASE"
echo "  [OK] Destination directory created: $DEST_BASE"

# ─── Reload system daemons ─────────────────────────────────────────────────────

udevadm control --reload-rules
systemctl daemon-reload
echo "  [OK] udev rules and systemd reloaded"

echo ""
echo "Installation complete!"
echo ""
echo "Test by connecting your camera, then check logs with:"
echo "  journalctl -u canon-camera-sync.service -f"
echo ""
echo "Or run the sync manually:"
echo "  sudo $SCRIPT_INSTALL_DIR/camera-sync.sh"
